FROM ruby:3.4.7-slim

RUN apt-get update -y && \
    apt-get install -y build-essential git curl nodejs npm \
    libssl-dev libpq-dev libvips sqlite3 imagemagick yarnpkg && \
    rm -rf /var/lib/apt/lists

WORKDIR /rails

ENV RAILS_ENV=production

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
